function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed");el.html("<span class=\"t142__text\">"+btntext+"</span>")}}}
function t190_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t391_checkSize(recid){var el=$("#rec"+recid);var cover=el.find('.t-cover');var carrier=el.find('.t-cover__carrier');var filter=el.find('.t-cover__filter');var height=el.find('.t391__firstcol').height()+el.find('.t391__secondcol').height();if(window.matchMedia('(max-width: 960px)').matches){cover.css('height',height);carrier.css('height',height);filter.css('height',height)}}
function t451_showMenu(recid){var el=$('#rec'+recid);$('body').addClass('t451__body_menushowed');el.find('.t451m').addClass('t451m__menu_show');el.find('.t451m__overlay').addClass('t451m__menu_show');el.find('.t451m__overlay, .t451m__close, .t451m__list_item, a[href*=#]').click(function(){t451_closeMenu()});$(document).keydown(function(e){if(e.keyCode==27){$('body').removeClass('t451__body_menushowed');$('.t451m').removeClass('t451m__menu_show');$('.t451m__overlay').removeClass('t451m__menu_show')}})}
function t451_closeMenu(){$('body').removeClass('t451__body_menushowed');$('.t451m').removeClass('t451m__menu_show');$('.t451m__overlay').removeClass('t451m__menu_show')}
function t451_checkSize(recid){var el=$('#rec'+recid).find('.t451m');var windowheight=$(window).height()-80;var contentheight=el.find(".t451m__top").height()+el.find(".t451m__rightside").height();if(contentheight>windowheight){el.addClass('t451m__overflowed');el.find(".t451m__container").css('height','auto')}}
function t451_initMenu(recid){var el=$('#rec'+recid);var obj=el.find('.t451__burger');obj.click(function(e){t451_closeMenu();t451_showMenu(recid);t451_checkSize(recid);e.preventDefault()})}
function t451_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t451__list_item a[href='"+url+"']").addClass("t-active");$(".t451__list_item a[href='"+url+"/']").addClass("t-active");$(".t451__list_item a[href='"+pathname+"']").addClass("t-active");$(".t451__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t451__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t451__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t451_changeBgOpacityMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t451__container__bg").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacity=el.attr("data-bgopacity");var bgopacity_afterscroll=el.attr("data-bgopacity2");var menu_shadow=el.attr("data-menu-shadow");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacity_afterscroll!="0"&&bgopacity_afterscroll!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}else{el.css("background-color",bgcolor);if(bgopacity!="0"&&bgopacity!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}})}
function t451_appearMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t451__panel").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");console.log(appearoffset)
if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t451__beforeready')){el.removeClass('t451__beforeready')}}else{el.addClass('t451__beforeready')}}})}
function t466_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t466__item a[href='"+url+"']").addClass("t-active");$(".t466__item a[href='"+url+"/']").addClass("t-active");$(".t466__item a[href='"+pathname+"']").addClass("t-active");$(".t466__item a[href='/"+pathname+"']").addClass("t-active");$(".t466__item a[href='"+pathname+"/']").addClass("t-active");$(".t466__item a[href='/"+pathname+"/']").addClass("t-active")}
function t466_checkAnchorLinks(recid){if($(window).width()>=960){var t466_navLinks=$("#rec"+recid+" .t466__menu a:not(.tooltipstered)[href*='#']");if(t466_navLinks.length>0){t466_catchScroll(t466_navLinks)}}}
function t466_catchScroll(t466_navLinks){var t466_clickedSectionId=null,t466_sections=new Array(),t466_sectionIdTonavigationLink={},t466_interval=100,t466_lastCall,t466_timeoutId,t466_offsetTop=$(".t466").attr("data-offset-top");if(typeof t466_offsetTop=="undefined"){t466_offsetTop=0}
t466_navLinks=$(t466_navLinks.get().reverse());t466_navLinks.each(function(){var t466_cursection=t466_getSectionByHref($(this));if(typeof t466_cursection.attr("id")!="undefined"){t466_sections.push(t466_cursection)}
t466_sectionIdTonavigationLink[t466_cursection.attr("id")]=$(this)});t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop);t466_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t466_navLinks.removeClass('t-active');t466_sectionIdTonavigationLink[t466_getSectionByHref($(this)).attr("id")].addClass('t-active');t466_clickedSectionId=t466_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t466_now=new Date().getTime();if(t466_lastCall&&t466_now<(t466_lastCall+t466_interval)){clearTimeout(t466_timeoutId);t466_timeoutId=setTimeout(function(){t466_lastCall=t466_now;t466_clickedSectionId=t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop)},t466_interval-(t466_now-t466_lastCall))}else{t466_lastCall=t466_now;t466_clickedSectionId=t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop)}})}
function t466_getSectionByHref(curlink){if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curlink.attr("href").substring(1)+"']")}
else{return $(".r[data-record-type='215']").has("a[name='"+curlink.attr("href").substring(1)+"']")}}
function t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,offsetTop){var t466_scrollPosition=$(window).scrollTop(),t466_valueToReturn=t466_clickedSectionId;$(t466_sections).each(function(e){var t466_curSection=$(this),t466_sectionTop=t466_curSection.offset().top,t466_id=t466_curSection.attr('id'),t466_navLink=t466_sectionIdTonavigationLink[t466_id];if(t466_scrollPosition>=(t466_sectionTop-offsetTop)||(t466_sections[0].attr("id")==t466_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t466_clickedSectionId==null&&!t466_navLink.hasClass('t-active')){t466_navLinks.removeClass('t-active');t466_navLink.addClass('t-active');t466_valueToReturn=null}else{if(t466_clickedSectionId!=null&&t466_id==t466_clickedSectionId){t466_valueToReturn=null}}
return!1}});return t466_valueToReturn}
function t466_initMobileMenu(recid){var window_width=$(window).width();var el=$("#rec"+recid);if(980>window_width){el.find(".t466").each(function(){$(this).find(".t466__mobile").css("top",$(this).find(".t466__container__bg_main").innerHeight()+2);$(this).find(".t466__burger, .t466__item:not('.tooltipstered')").click(function(){$("body").toggleClass('t466_opened');$(this).closest(".t466").find(".t466__mobile").slideToggle(300)})})}}
function t466_appearMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t466").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t466__beforeready')){el.removeClass('t466__beforeready')}}else{el.addClass('t466__beforeready')}}})}
function t466_changeBgOpacityMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t466__container__bg").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacity=el.attr("data-bgopacity");var bgopacity_afterscroll=el.attr("data-bgopacity2");var menu_shadow=el.attr("data-menu-shadow");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacity_afterscroll!="0"&&bgopacity_afterscroll!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}else{el.css("background-color",bgcolor);if(bgopacity!="0"&&bgopacity!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}})}
function t576_init(recid){var el=$('#rec'+recid),line=el.find('.t576__line'),cirqle=el.find('.t576__cicqle'),block=el.find('.t576__item'),t576_resize;block.each(function(){$(this).find('.t576__circle').css('top',$(this).find('.t576__img').outerHeight()+15)});$('.t576__item:first-child').find('.t576__line').css('top',$('.t576__item:first-child').find('.t576__img').outerHeight()+15);$('.t576__item:last-child').find('.t576__line').css('height',$('.t576__item:last-child').find('.t576__img').outerHeight()+20)}
function t675_init(recid){var el=$("#rec"+recid),textwrapper=el.find('.t675__textwrapper'),dots=el.find('.t-slds__bullet_wrapper');textwrapper.css('margin-bottom',dots.outerHeight()+7)}
function t770_init(recid){var rec=$('#rec'+recid);var navElem=rec.find('.t770');var isFixed=(navElem.css('position')=='fixed');var redactorMode=navElem.hasClass('t770_redactor-mode');if(!redactorMode){t770_highlight();if(isFixed){t770_checkAnchorLinks(recid)}
if(isFixed&&navElem.attr('data-bgopacity-two')){t770_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t770_changebgopacitymenu(recid)},200))}
if(isFixed&&navElem.attr('data-appearoffset')){navElem.removeClass('t770__beforeready');t770_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t770_appearMenu(recid)},200))}}
if(rec.find('.t770__imglogo').attr('data-img-width')){t770_setLogoPadding(recid)}
if(rec.find('.t770__mobile_burger').length){t770_createMobileMenu(recid)}
t770_setBg(recid);$(window).bind('resize',t_throttle(function(){t770_setBg(recid)},200))}
function t770_setLogoPadding(recid){if($(window).width()>980){var t770__menu=$('#rec'+recid+' .t770');var t770__logo=t770__menu.find('.t770__logowrapper');var t770__leftpart=t770__menu.find('.t770__leftwrapper');var t770__rightpart=t770__menu.find('.t770__rightwrapper');t770__leftpart.css("padding-right",t770__logo.width()/2+50);t770__rightpart.css("padding-left",t770__logo.width()/2+50)}}
function t770_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t770__list_item a[href='"+url+"']").addClass("t-active");$(".t770__list_item a[href='"+url+"/']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t770__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t770_checkAnchorLinks(recid){if($(window).width()>=960){var t770_navLinks=$("#rec"+recid+" .t770__desktoplist .t770__list_item a:not(.tooltipstered)[href*='#']");if(t770_navLinks.length>0){t770_catchScroll(t770_navLinks)}}}
function t770_catchScroll(t770_navLinks){var t770_clickedSectionId=null,t770_sections=new Array(),t770_sectionIdTonavigationLink=[],t770_interval=100,t770_lastCall,t770_timeoutId;t770_navLinks=$(t770_navLinks.get().reverse());t770_navLinks.each(function(){var t770_cursection=t770_getSectionByHref($(this));if(typeof t770_cursection.attr("id")!="undefined"){t770_sections.push(t770_cursection)}
t770_sectionIdTonavigationLink[t770_cursection.attr("id")]=$(this)});t770_updateSectionsOffsets(t770_sections);t770_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t770_updateSectionsOffsets(t770_sections)},200));$('.t770').bind('displayChanged',function(){t770_updateSectionsOffsets(t770_sections)});setInterval(function(){t770_updateSectionsOffsets(t770_sections)},5000);t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId);t770_navLinks.click(function(){var t770_clickedSection=t770_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t770_clickedSection.attr("id")!="undefined"){t770_navLinks.removeClass('t-active');$(this).addClass('t-active');t770_clickedSectionId=t770_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t770_now=new Date().getTime();if(t770_lastCall&&t770_now<(t770_lastCall+t770_interval)){clearTimeout(t770_timeoutId);t770_timeoutId=setTimeout(function(){t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)},t770_interval-(t770_now-t770_lastCall))}else{t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)}})}
function t770_updateSectionsOffsets(sections){$(sections).each(function(){var t770_curSection=$(this);t770_curSection.attr("data-offset-top",t770_curSection.offset().top)})}
function t770_getSectionByHref(curlink){var t770_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t770_curLinkValue[0]=='/'){t770_curLinkValue=t770_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t770_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t770_curLinkValue.substring(1)+"']")}}
function t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId){var t770_scrollPosition=$(window).scrollTop(),t770_valueToReturn=t770_clickedSectionId;if(t770_sections.length!=0&&t770_clickedSectionId==null&&t770_sections[t770_sections.length-1].attr("data-offset-top")>(t770_scrollPosition+300)){t770_navLinks.removeClass('t-active');return null}
$(t770_sections).each(function(e){var t770_curSection=$(this),t770_sectionTop=t770_curSection.attr("data-offset-top"),t770_id=t770_curSection.attr('id'),t770_navLink=t770_sectionIdTonavigationLink[t770_id];if(((t770_scrollPosition+300)>=t770_sectionTop)||(t770_sections[0].attr("id")==t770_id&&t770_scrollPosition>=$(document).height()-$(window).height())){if(t770_clickedSectionId==null&&!t770_navLink.hasClass('t-active')){t770_navLinks.removeClass('t-active');t770_navLink.addClass('t-active');t770_valueToReturn=null}else{if(t770_clickedSectionId!=null&&t770_id==t770_clickedSectionId){t770_valueToReturn=null}}
return!1}});return t770_valueToReturn}
function t770_setPath(){}
function t770_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t770_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t770_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t770_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t770"),burger=el.find(".t770__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t770_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}